spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mambu_mock}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:mambu_mock}
    password: ${DB_PASSWORD:mambu_mock}

  h2:
    console:
      enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
