-- ============================================================
-- V3: Mambu Mock — Clients (Borrowers)
-- Mirrors Mambu Client object
-- ============================================================

CREATE TABLE IF NOT EXISTS mambu_clients (
    encoded_key             VARCHAR(64)     NOT NULL PRIMARY KEY,
    client_id               VARCHAR(100)    NOT NULL UNIQUE,
    first_name              VARCHAR(255)    NOT NULL,
    last_name               VARCHAR(255),
    full_name               VARCHAR(511),
    email_address           VARCHAR(255),
    mobile_phone            VARCHAR(50),
    birth_date              DATE,
    gender                  VARCHAR(20),
    state                   VARCHAR(50)     NOT NULL DEFAULT 'ACTIVE',
    assigned_branch_key     VARCHAR(64),
    notes                   TEXT,
    creation_date           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_date      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mambu_client_id_documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_encoded_key  VARCHAR(64)     NOT NULL,
    document_type       VARCHAR(100)    NOT NULL,
    document_id         VARCHAR(255)    NOT NULL,
    issuing_authority   VARCHAR(255),
    issue_date          DATE,
    expiry_date         DATE,
    CONSTRAINT fk_id_doc_client FOREIGN KEY (client_encoded_key) REFERENCES mambu_clients(encoded_key)
);

CREATE TABLE IF NOT EXISTS mambu_client_addresses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_encoded_key  VARCHAR(64)     NOT NULL,
    line1               VARCHAR(255),
    line2               VARCHAR(255),
    city                VARCHAR(100),
    region              VARCHAR(100),
    postcode            VARCHAR(20),
    country             VARCHAR(100),
    index_in_list       INT             DEFAULT 0,
    CONSTRAINT fk_address_client FOREIGN KEY (client_encoded_key) REFERENCES mambu_clients(encoded_key)
);

CREATE INDEX IF NOT EXISTS idx_client_id ON mambu_clients(client_id);
CREATE INDEX IF NOT EXISTS idx_client_branch ON mambu_clients(assigned_branch_key);
