-- ============================================================
-- V5: Mambu Mock — Installments + Transactions
-- ============================================================

CREATE TABLE IF NOT EXISTS mambu_installments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_encoded_key        VARCHAR(64)     NOT NULL,
    installment_number      INT             NOT NULL,
    due_date                DATE            NOT NULL,
    state                   VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    -- Principal
    principal_amount        DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    principal_paid          DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    principal_due           DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    -- Interest
    interest_amount         DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    interest_paid           DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    interest_due            DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    -- Fee
    fee_amount              DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    fee_paid                DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    fee_due                 DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    -- Penalty
    penalty_amount          DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    penalty_paid            DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    penalty_due             DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    -- Total
    total_due               DECIMAL(18, 2)  NOT NULL DEFAULT 0,
    last_paid_date          DATE,

    CONSTRAINT fk_installment_loan FOREIGN KEY (loan_encoded_key) REFERENCES mambu_loan_accounts(encoded_key),
    CONSTRAINT uq_installment UNIQUE (loan_encoded_key, installment_number)
);

CREATE TABLE IF NOT EXISTS mambu_transactions (
    encoded_key         VARCHAR(64)     NOT NULL PRIMARY KEY,
    transaction_id      VARCHAR(100)    NOT NULL UNIQUE,
    type                VARCHAR(100)    NOT NULL,   -- DISBURSEMENT, REPAYMENT, FEE, PENALTY
    amount              DECIMAL(18, 2)  NOT NULL,
    parent_account_key  VARCHAR(64)     NOT NULL,
    parent_account_id   VARCHAR(100)    NOT NULL,
    external_id         VARCHAR(255),
    notes               TEXT,
    channel_id          VARCHAR(100)    DEFAULT 'ONLINE_PAYMENT',
    value_date          DATE            NOT NULL,
    creation_date       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_txn_loan FOREIGN KEY (parent_account_key) REFERENCES mambu_loan_accounts(encoded_key)
);

CREATE INDEX IF NOT EXISTS idx_installment_loan   ON mambu_installments(loan_encoded_key);
CREATE INDEX IF NOT EXISTS idx_installment_state  ON mambu_installments(state);
CREATE INDEX IF NOT EXISTS idx_txn_id             ON mambu_transactions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_txn_loan           ON mambu_transactions(parent_account_key);
CREATE INDEX IF NOT EXISTS idx_txn_external       ON mambu_transactions(external_id);
